### ISSUE TITLE
byteball app got crashed during steem attestation process

### ISSUE THREAD

**Issue by dakeshi** [byteball/steem-attestation#1]
When I return back to the back after I has completed steem-connect, byteball app got crashed showing this message in the screen.

![byteball_crash](https://user-images.githubusercontent.com/8563047/42665097-fd3ea5e4-8678-11e8-9d38-a77aaa40d89c.png)

the whole error message:
An exception occurred: Error: [$parse:syntax] Syntax Error: Token ']' is unexpected, expecting [)] at column 47 of the expression [sendPayment('myWalletAddress']</a>] starting at []</a>]. http://errors.angularjs.org/1.6.6/$parse/syntax?p0=%5D&p1=is%20unexpected%2C%20expecting%20%5B)%5D&p2=47&p3=sendPayment('myWalletAddress'%5D%3C%2Fa%3E&p4=%5D%3C%2Fa%3E; cause: <a ng-click="sendPayment('myWalletAddress']</a>

There are no problems with 2.4.0 version.

testing env: macOS
byteball version: 2.3.0(Mac version)

**Comment by STEPHDEMA** [comment]
I have the same message!

**Comment by tarmo888** [comment]
Steem attestation requires v2.4.0 wallet, it does not work on old v2.3.0

**Comment by dakeshi** [comment]
> Steem attestation requires v2.4.0 wallet, it does not work on old v2.3.0

checked.
